<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="UCLoginTest"
           tests="3"
           failures="2"
           errors="0"
           skipped="0"
           time="20.791">
  <properties />
            <testcase name="InputRightPwdTest" time="8.985" classname="cases.UCLoginTest">
                <failure type="java.lang.Exception"
                  message="[失败]assertTrue操作异常：
Expected: is &lt;true&gt;
     got: &lt;false&gt;
,实际值:false,期望值:true"
              >
<![CDATA[java.lang.Exception: [失败]assertTrue操作异常：
Expected: is <true>
     got: <false>
,实际值:false,期望值:true
  com.zendaimoney.Dokodemo.logger.LogUtils.setAssertFailed(LogUtils.java:382)
  com.zendaimoney.Dokodemo.DokodemoTool.assertTrue(DokodemoTool.java:69)
  com.zendaimoney.Dokodemo.ETestWebUIBaseCase.assertTrue(ETestWebUIBaseCase.java:44)
  cases.UCLoginTest.InputRightPwdTest(UCLoginTest.java:54)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:606)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
  org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
  java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
  java.util.concurrent.FutureTask.run(FutureTask.java:166)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
  java.lang.Thread.run(Thread.java:724)
]]>
      </failure>

          </testcase>
            <testcase name="InputWrongPwdTest" time="9.012" classname="cases.UCLoginTest">
                <failure type="java.lang.Exception"
                  message="[失败]assertTrue操作异常：
Expected: is &lt;true&gt;
     got: &lt;false&gt;
,实际值:false,期望值:true"
              >
<![CDATA[java.lang.Exception: [失败]assertTrue操作异常：
Expected: is <true>
     got: <false>
,实际值:false,期望值:true
  com.zendaimoney.Dokodemo.logger.LogUtils.setAssertFailed(LogUtils.java:382)
  com.zendaimoney.Dokodemo.DokodemoTool.assertTrue(DokodemoTool.java:69)
  com.zendaimoney.Dokodemo.ETestWebUIBaseCase.assertTrue(ETestWebUIBaseCase.java:44)
  cases.UCLoginTest.InputWrongPwdTest(UCLoginTest.java:45)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:606)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
  org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
  java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
  java.util.concurrent.FutureTask.run(FutureTask.java:166)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
  java.lang.Thread.run(Thread.java:724)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="InputNullPwdTest" time="2.794" classname="cases.UCLoginTest" />
      
</testsuite>
