<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="admin-PC" name="cases.Fortune_loginText" tests="3" failures="2" timestamp="23 Jun 2014 06:12:13 GMT" time="62.272" errors="0">
  <testcase name="InputNullPwdTest" time="15.541" classname="cases.Fortune_loginText"/>
  <testcase name="InputWrongPwdTest" time="29.833" classname="cases.Fortune_loginText">
    <failure type="java.lang.Exception" message="[失败]assertTrue操作异常：
Expected: is &lt;true&gt;
     got: &lt;false&gt;
,实际值:false,期望值:true">
      <![CDATA[java.lang.Exception: [失败]assertTrue操作异常：
Expected: is <true>
     got: <false>
,实际值:false,期望值:true
	at com.zendaimoney.Dokodemo.logger.LogUtils.setAssertFailed(LogUtils.java:382)
	at com.zendaimoney.Dokodemo.DokodemoTool.assertTrue(DokodemoTool.java:69)
	at com.zendaimoney.Dokodemo.ETestWebUIBaseCase.assertTrue(ETestWebUIBaseCase.java:44)
	at cases.Fortune_loginText.InputWrongPwdTest(Fortune_loginText.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
]]>
    </failure>
  </testcase> <!-- InputWrongPwdTest -->
  <testcase name="InputRightPwdTest" time="16.898" classname="cases.Fortune_loginText">
    <failure type="java.lang.Exception" message="[失败]assertTrue操作异常：
Expected: is &lt;true&gt;
     got: &lt;false&gt;
,实际值:false,期望值:true">
      <![CDATA[java.lang.Exception: [失败]assertTrue操作异常：
Expected: is <true>
     got: <false>
,实际值:false,期望值:true
	at com.zendaimoney.Dokodemo.logger.LogUtils.setAssertFailed(LogUtils.java:382)
	at com.zendaimoney.Dokodemo.DokodemoTool.assertTrue(DokodemoTool.java:69)
	at com.zendaimoney.Dokodemo.ETestWebUIBaseCase.assertTrue(ETestWebUIBaseCase.java:44)
	at cases.Fortune_loginText.InputRightPwdTest(Fortune_loginText.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
]]>
    </failure>
  </testcase> <!-- InputRightPwdTest -->
</testsuite> <!-- cases.Fortune_loginText -->
